### ISSUE TITLE
What I am doing wrong?

### ISSUE THREAD

**Issue by DavidCrediverso** [juntossomosmais/django-stomp#53] opened 2022-07-25 23:01 UTC
I have a code

```
AMQHOST = 'mq.website.com'
AMQPORT = '61614'
AMQUSER = 'website-int'
AMQPASS = '123456'
TOPICNAME = '/topic/website.integration.customer'

hosts = [(AMQHOST, AMQPORT)]
conn = stomp.Connection(host_and_ports=hosts, use_ssl=True)
conn.set_listener('stomp_listener', MsgListener())
conn.connect(AMQUSER, AMQPASS, wait=True, headers={'client-id': 'website'})
conn.subscribe(destination=TOPICNAME, id=1, ack='auto')
time.sleep(10)  # secs
conn.disconnect()
```

It's working,

but trying the same with **django-stomp** it's impossible to do. Please tell me what I am doing wrong.

```
STOMP_SERVER_HOST = 'mq.website.com'
STOMP_SERVER_PORT = '61614'
STOMP_SERVER_USER = 'website-int'
STOMP_SERVER_PASSWORD = '123456'
STOMP_USE_SSL = True
STOMP_LISTENER_CLIENT_ID = 'website'
Terminal> python3 manage.py pubsub "/topic/website.integration.customer" app.message_queue.message_queue_logic

```
I have error:
'User website-int is not authorized to read from: queue://DLQ.website.integration.customer'

Thanks

**Comment by willianantunes** [comment] 2022-07-26 17:59
Hi @DavidCrediverso. The following error:

> User _website-int_ is not authorized to read from: queue://DLQ.website.integration.customer

This error has nothing to do with Django STOMP. It's related to the broker you are connecting to. Which one are you using?

**Comment by willianantunes** [comment] 2022-07-26 18:02
Hi @DavidCrediverso. How about using your code to connect to the DQL? It connects to `/topic/website.integration.customer` only. So, the following error:

> User _website-int_ is not authorized to read from: queue://DLQ.website.integration.customer

It has nothing to do with Django STOMP. It's related to the broker you are connecting to.

**Comment by DavidCrediverso** [comment] 2022-07-29 22:02
I have only this information from the service side. When I am testing, it works with stomp. I want to use django-stomp for that.

**Comment by DavidCrediverso** [comment] 2022-08-03 18:44
Can you help me, or what do I need to ask of the team who gave me these parameters?

**Comment by willianantunes** [comment] 2022-08-04 12:24
@DavidCrediverso which broker are you using? Is it ActiveMQ or RabbitMQ?

Did you try to emulate locally using Docker? _Django STOMP_ uses a real RabbitMQ (look at it [here](https://github.com/juntossomosmais/django-stomp/blob/e7d3c546cd2777186dba95169c03b334a3507e9c/docker-compose.yml#L17-L23) in the docker compose file) to guarantee its business rules. We can do the same thing to test yours.

> Can you help me, or what do I need to ask of the team who gave me these parameters?

Like I said, it seems the issue is on the broker side. To be totally sure about it, you can emulate locally and understand what is happening. Can you do that?

**Comment by DavidCrediverso** [comment] 2022-08-04 21:44
My company bought a service from another company, and they gave me these parameters for connections. They are using ActiveMQ. I tested how it works by using the stomp library, and I received all the messages, so it's working. I have a project in Django and I want to use this Django-stomp, but using the same parameters, I can't receive messages. I can't run a broker locally. If the issue is on the broker's side, why is the stomp library working? Maybe the problem is with replacing DLQ or with subscriptions. [Here is](https://developer.rizefs.com/docs/subscriptions) how it works.

**Comment by willianantunes** [comment] 2022-08-09 12:03
@DavidCrediverso did you read the [known limitations](https://github.com/juntossomosmais/django-stomp#known-limitations) sections?

> If the issue is on the broker's side, why is the stomp library working?

Like I said [here](https://github.com/juntossomosmais/django-stomp/issues/53#issuecomment-1195809300), you tested it considering only one destination, but _Django STOMP_ uses two: one main destinations and its DLQ. You didn't test the full cycle.

> I can't run a broker locally.

You can use a container engine, so you don't need to install the broker or something.

I'll create a repository with your scenario when I have time. I'll let you know here. By the way, I wrote a blog post about [transactions with STOMP](https://www.willianantunes.com/blog/2022/01/using-transactions-with-stomp-with-the-help-of-django-stomp/). Maybe you can use [this project](https://github.com/willianantunes/tutorials/tree/master/2022/01/transactions-with-django-stomp) and figure out what is missing in yours.

**Comment by willianantunes** [comment] 2023-08-17 17:57
Closing it as we don't receive any more inputs.

**Closed by willianantunes** 2023-08-17 17:57 UTC
Labels: question
